# Generated by Django 4.2.3 on 2023-08-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='emai',
            new_name='email',
        ),
    ]
