# Generated by Django 4.2.3 on 2023-08-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_rename_emai_alumno_email_rename_emai_profesor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='telefono',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='telefono',
            new_name='dni',
        ),
    ]
