# Generated by Django 4.2.3 on 2023-08-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_profesor_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='materia',
            field=models.CharField(default='', max_length=40),
        ),
    ]
